# swagger.yaml
openapi: 3.0.0
info:
  title: force 
  version: 1.0.0
  description: API documentation for the Customer Growth Calculator
servers:
  - url: 'http://localhost:7000/api'
paths:
  /growth:
    post:
      summary: Calculate customer growth
      tags: [Growth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                initialCustomers:
                  type: integer
                startDate:
                  type: string
                  format: date
                monthlyGrowthRate:
                  type: number
      responses:
        200:
          description: Growth calculated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
  /growth/{id}/month:
    put:
      summary: Update growth rate for a specific month
      tags: [Growth]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                monthIndex:
                  type: integer
                newRate:
                  type: number
      responses:
        200:
          description: Growth rate updated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
  /growth/{id}/future:
    put:
      summary: Update growth rate for all future months
      tags: [Growth]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yearIndex:
                  type: integer
                newRate:
                  type: number
      responses:
        200:
          description: Growth rate for future months updated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
